version: "3.10.12"

services:
  flask_api:
    container_name: flask_api
    image: corradot/flask_api_app:1.0.0
    build: .
    ports:
      - "6000:6000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
#      - FLASK_APP=flask_api.py
    depends_on:
      flask_db:
        condition: service_healthy
#    networks:
#      - mynet
  flask_db:
    container_name: flask_db
    image: postgres:12
#    hostname: flask_db
    ports:
      - "5432:5432"
#    expose:
#      - 5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
#    networks:
#      mynet:
##        aliases:
##          - flask_db
#networks:
#  mynet:

volumes:
  pgdata: {}