version: "3"

services:
  flask-db:
    container_name: flask-db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  flask-api:
    container_name: flask-api
    image: thekube/flask-api-app:latest
    build: .
    ports:
      - "6000:6000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask-db:5432/postgres
    restart: always
volumes:
  pgdata: {}