POST http://127.0.0.1:6000/user HTTP/1.1
content-type: application/json

{
  "username": "bob john",
  "email": "abcd@mail.com"
}
###
GET http://127.0.0.1:6000/users HTTP/1.1
###
GET http://127.0.0.1:6000/users/1 HTTP/1.1
###
DELETE http://127.0.0.1:6000/user/1 HTTP/1.1
###
PUT http://127.0.0.1:6000/user/39 HTTP/1.1
###
GET http://127.0.0.1:6000/health HTTP/1.1
###
GET http://127.0.0.1:6000/details HTTP/1.1
###