apiVersion: v1
kind: Service
metadata:
  name: {{ include "flapp.fullname" . }}-api
  labels:
    io.kompose.service: flask-api
  {{- include "flapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.type }}
  selector:
    app: flask-api
  {{- include "flapp.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.api.ports | toYaml | nindent 2 -}}