apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "apiapp.fullname" . }}-api-ingress
  labels:
  {{- include "apiapp.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: nginx
  rules:
  - host: corradoapiapp.io
    http:
      paths:
      - backend:
          service:
            name: '{{ include "apiapp.fullname" . }}-api'
            port:
              number: 6000
        path: /
        pathType: Prefix