apiVersion: v1
kind: Service
metadata:
  name: {{ include "apiapp.fullname" . }}-api
  labels:
    io.kompose.service: flask-api
  {{- include "apiapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.type }}
  selector:
    app: flask-api
  {{- include "apiapp.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.api.ports | toYaml | nindent 2 -}}