apiVersion: v1
kind: Service
metadata:
  name: {{ include "apiapp.fullname" . }}-db
  labels:
    io.kompose.service: flask-db
  {{- include "apiapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.db.type }}
  selector:
    app: flask-db
  {{- include "apiapp.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.db.ports | toYaml | nindent 2 -}}